
version: 2

models:
  - name: trusted_to_spec
    description: "Creation of the satisfaction table on the gold layer."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null